"""Additional preconditioning utilities for meta-learning.

Complements the low-rank preconditioner with lighter-weight alternatives:

* :class:`DiagonalPreconditioner` — per-coordinate adaptive scaling, similar
  to Adam's second-moment normalisation but *learned*.
* :class:`KroneckerPreconditioner` — Kronecker-factored curvature
  approximation (KFAC-style) for weight matrices, decomposing ``M`` as
  ``A ⊗ B`` to reduce memory from O(d²) to O(d_in² + d_out²).

Both accept the same ``(h, E)`` context inputs as
:class:`~remap_net.meta_learning.low_rank.LowRankPreconditioner`.
"""

from __future__ import annotations

import math

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import Tensor


class DiagonalPreconditioner(nn.Module):
    r"""Context-conditioned diagonal preconditioning.

    Generates a positive diagonal scaling vector ``d(h, E) ∈ ℝ^{param_dim}``
    via a small MLP + softplus, yielding ``M = diag(d)``.

    This is the cheapest preconditioner — O(d) parameters and O(d) compute
    — making it suitable for very high-dimensional parameter vectors where
    even the low-rank factorisation is too expensive.

    Args:
        param_dim: Dimension of the parameter vector.
        context_dim: Combined dimension of ``[h; E]``.
        hidden_dim: MLP hidden width.

    Shape:
        - h: ``(batch, history_dim)``
        - E: ``(batch, episodic_dim)``
        - Output: ``(batch, param_dim)``  (diagonal entries, **not** the full
          ``d × d`` matrix).
    """

    def __init__(
        self,
        param_dim: int,
        context_dim: int = 128,
        hidden_dim: int = 128,
    ) -> None:
        super().__init__()
        self.param_dim = param_dim

        self.net = nn.Sequential(
            nn.Linear(context_dim, hidden_dim),
            nn.SiLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.SiLU(),
            nn.Linear(hidden_dim, param_dim),
        )

        # Learnable base scale (log-space).
        self.log_base_scale = nn.Parameter(torch.zeros(param_dim))

        self._init_weights()

    def _init_weights(self) -> None:
        for module in self.net.modules():
            if isinstance(module, nn.Linear):
                nn.init.kaiming_uniform_(module.weight, a=math.sqrt(5))
                if module.bias is not None:
                    nn.init.zeros_(module.bias)
        # Output layer near zero so initial scaling ≈ softplus(base_scale).
        last = self.net[-1]
        assert isinstance(last, nn.Linear)
        last.weight.data.mul_(0.01)

    def forward(self, h: Tensor, E: Tensor) -> Tensor:
        """Compute positive diagonal scaling.

        Args:
            h: Gradient history encoding, ``(batch, history_dim)``.
            E: Episodic context, ``(batch, episodic_dim)``.

        Returns:
            Diagonal scaling vector of shape ``(batch, param_dim)``, strictly
            positive.
        """
        ctx = torch.cat([h, E], dim=-1)
        raw = self.net(ctx) + self.log_base_scale  # (B, d)
        return F.softplus(raw)  # ensure positivity

    def forward_as_matrix(self, h: Tensor, E: Tensor) -> Tensor:
        """Return the full diagonal matrix (for interface compatibility).

        Returns:
            ``(batch, param_dim, param_dim)`` diagonal matrix.
        """
        diag = self.forward(h, E)
        return torch.diag_embed(diag)


class KroneckerPreconditioner(nn.Module):
    r"""Kronecker-factored preconditioning for weight matrices.

    For a weight matrix ``W ∈ ℝ^{d_out × d_in}``, the full preconditioning
    matrix ``M ∈ ℝ^{(d_out · d_in) × (d_out · d_in)}`` is approximated as:

        M ≈ A ⊗ B

    where ``A ∈ ℝ^{d_out × d_out}`` and ``B ∈ ℝ^{d_in × d_in}`` are
    generated by small context-conditioned networks.

    This reduces memory from ``O((d_out · d_in)²)`` to
    ``O(d_out² + d_in²)`` while preserving inter-coordinate coupling.

    The Kronecker product ``(A ⊗ B) · vec(G) = vec(B · G · A^T)`` is
    computed efficiently without materialising the full product matrix.

    Args:
        d_in: Input dimension of the weight matrix.
        d_out: Output dimension of the weight matrix.
        context_dim: Combined dimension of ``[h; E]``.
        hidden_dim: Hyper-network hidden width.
    """

    def __init__(
        self,
        d_in: int,
        d_out: int,
        context_dim: int = 128,
        hidden_dim: int = 64,
    ) -> None:
        super().__init__()
        self.d_in = d_in
        self.d_out = d_out

        # Hyper-net for A ∈ ℝ^{d_out × d_out}.
        self.a_net = nn.Sequential(
            nn.Linear(context_dim, hidden_dim),
            nn.SiLU(),
            nn.Linear(hidden_dim, d_out * d_out),
        )
        # Hyper-net for B ∈ ℝ^{d_in × d_in}.
        self.b_net = nn.Sequential(
            nn.Linear(context_dim, hidden_dim),
            nn.SiLU(),
            nn.Linear(hidden_dim, d_in * d_in),
        )

        self.log_scale = nn.Parameter(torch.tensor(math.log(0.01)))

        self._init_weights()

    def _init_weights(self) -> None:
        for net in (self.a_net, self.b_net):
            for m in net.modules():
                if isinstance(m, nn.Linear):
                    nn.init.kaiming_uniform_(m.weight, a=math.sqrt(5))
                    if m.bias is not None:
                        nn.init.zeros_(m.bias)
            # Near-identity at init.
            last = net[-1]
            assert isinstance(last, nn.Linear)
            last.weight.data.mul_(0.01)
            if last.bias is not None:
                last.bias.data.zero_()

    def forward(
        self, h: Tensor, E: Tensor, gradient_matrix: Tensor
    ) -> Tensor:
        """Apply Kronecker-factored preconditioning to a gradient matrix.

        Instead of materialising the ``(d_out·d_in) × (d_out·d_in)`` matrix,
        computes the product efficiently:

            (A ⊗ B) · vec(G) = vec(B · G · A^T)

        Args:
            h: Gradient history encoding, ``(batch, history_dim)``.
            E: Episodic context, ``(batch, episodic_dim)``.
            gradient_matrix: Gradient **in matrix form**,
                ``(batch, d_out, d_in)``.

        Returns:
            Preconditioned gradient, ``(batch, d_out, d_in)``.
        """
        ctx = torch.cat([h, E], dim=-1)
        B = ctx.shape[0]
        scale = self.log_scale.exp()

        # Generate factors.
        A_raw = self.a_net(ctx).view(B, self.d_out, self.d_out)
        B_raw = self.b_net(ctx).view(B, self.d_in, self.d_in)

        # Add identity for stability (so init ≈ identity preconditioning).
        A = (
            A_raw * scale
            + torch.eye(self.d_out, device=ctx.device, dtype=ctx.dtype)
        )
        B_mat = (
            B_raw * scale
            + torch.eye(self.d_in, device=ctx.device, dtype=ctx.dtype)
        )

        # Efficient Kronecker application: vec(B_mat · G · A^T).
        preconditioned = torch.bmm(
            B_mat, torch.bmm(gradient_matrix, A.transpose(1, 2))
        )

        return preconditioned

    def get_factors(
        self, h: Tensor, E: Tensor
    ) -> tuple[Tensor, Tensor]:
        """Return the raw Kronecker factors for analysis.

        Returns:
            Tuple ``(A, B)`` of shapes ``(batch, d_out, d_out)`` and
            ``(batch, d_in, d_in)``.
        """
        ctx = torch.cat([h, E], dim=-1)
        B = ctx.shape[0]
        scale = self.log_scale.exp()

        A = self.a_net(ctx).view(B, self.d_out, self.d_out) * scale
        A = A + torch.eye(self.d_out, device=ctx.device, dtype=ctx.dtype)

        B_mat = self.b_net(ctx).view(B, self.d_in, self.d_in) * scale
        B_mat = B_mat + torch.eye(
            self.d_in, device=ctx.device, dtype=ctx.dtype
        )
        return A, B_mat
